"""
FreeRelay — OpenAI Wire Format (Pydantic v2)
==============================================
Matches the spec sections 6.1, 6.2, 6.3 exactly.
"""

from __future__ import annotations

import time
import uuid
from typing import Literal

from pydantic import BaseModel, Field

# ═══════════════════════════════════════════════════════════════════════
# REQUEST MODELS (§6.1)
# ═══════════════════════════════════════════════════════════════════════


class FunctionCall(BaseModel):
    """A function call generated by the model."""
    name: str
    arguments: str  # JSON string


class ToolCall(BaseModel):
    """A tool call generated by the model."""
    id: str
    type: Literal["function"] = "function"
    function: FunctionCall


class ContentPart(BaseModel):
    """Multi-modal content part (text or image)."""
    type: Literal["text", "image_url"]
    text: str | None = None
    image_url: dict[str, str] | None = None


class Message(BaseModel):
    """Chat message in OpenAI format."""
    role: Literal["system", "user", "assistant", "tool", "function"]
    content: str | list[ContentPart] | None = None
    name: str | None = None
    tool_calls: list[ToolCall] | None = None
    tool_call_id: str | None = None


class Function(BaseModel):
    """Function definition for tool use."""
    name: str
    description: str | None = None
    parameters: dict[str, object] | None = None


class Tool(BaseModel):
    """Tool definition — currently only function type."""
    type: Literal["function"] = "function"
    function: Function


class ResponseFormat(BaseModel):
    """Response format specification."""
    type: Literal["text", "json_object"] = "text"


class StreamOptions(BaseModel):
    """Options for streamed responses."""
    include_usage: bool = False


class ChatCompletionRequest(BaseModel):
    """
    Complete /v1/chat/completions request body.
    Every field from the OpenAI API reference.
    """
    model: str = ""
    messages: list[Message]
    temperature: float | None = None
    top_p: float | None = None
    n: int | None = 1
    stream: bool | None = False
    stop: str | list[str] | None = None
    max_tokens: int | None = None
    presence_penalty: float | None = None
    frequency_penalty: float | None = None
    logit_bias: dict[str, float] | None = None
    logprobs: bool | None = None
    top_logprobs: int | None = None
    user: str | None = None
    tools: list[Tool] | None = None
    tool_choice: str | dict[str, object] | None = None
    response_format: ResponseFormat | None = None
    seed: int | None = None
    stream_options: StreamOptions | None = None

    model_config = {"extra": "allow"}

    def is_streaming(self) -> bool:
        """Check if this request asks for streaming."""
        return self.stream is True

    def get_content_text(self) -> str:
        """Extract all text content from messages for hashing/classification."""
        parts: list[str] = []
        for msg in self.messages:
            if isinstance(msg.content, str):
                parts.append(msg.content)
            elif isinstance(msg.content, list):
                for p in msg.content:
                    if p.text:
                        parts.append(p.text)
        return "\n".join(parts)

    def estimate_tokens(self) -> int:
        """Rough token estimate: ~4 chars per token."""
        return max(1, len(self.get_content_text()) // 4)


# ═══════════════════════════════════════════════════════════════════════
# RESPONSE MODELS (§6.2)
# ═══════════════════════════════════════════════════════════════════════


class Usage(BaseModel):
    """Token usage statistics."""
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0


class LogprobContent(BaseModel):
    """Log probability for a single token."""
    token: str
    logprob: float
    bytes: list[int] | None = None
    top_logprobs: list[dict[str, object]] | None = None


class Logprobs(BaseModel):
    """Log probability information for a choice."""
    content: list[LogprobContent] | None = None


class Choice(BaseModel):
    """A single completion choice."""
    index: int
    message: Message
    finish_reason: str | None = None
    logprobs: Logprobs | None = None


class ChatCompletionResponse(BaseModel):
    """
    Complete /v1/chat/completions response body.
    """
    id: str = Field(default_factory=lambda: f"chatcmpl-{uuid.uuid4().hex[:24]}")
    object: Literal["chat.completion"] = "chat.completion"
    created: int = Field(default_factory=lambda: int(time.time()))
    model: str = ""
    choices: list[Choice] = Field(default_factory=list)
    usage: Usage = Field(default_factory=Usage)
    system_fingerprint: str | None = None

    model_config = {"extra": "allow"}

    @classmethod
    def from_text(
        cls,
        content: str,
        model: str = "",
        usage: Usage | None = None,
        finish_reason: str = "stop",
    ) -> ChatCompletionResponse:
        """Convenience: build a simple text response."""
        return cls(
            model=model,
            choices=[
                Choice(
                    index=0,
                    message=Message(role="assistant", content=content),
                    finish_reason=finish_reason,
                )
            ],
            usage=usage or Usage(),
        )

    @classmethod
    def error_body(cls, message: str, code: int = 500) -> dict[str, object]:
        """Build an OpenAI-style error body (not a ChatCompletionResponse)."""
        return {
            "error": {
                "message": message,
                "type": "server_error",
                "param": None,
                "code": code,
            }
        }


# ═══════════════════════════════════════════════════════════════════════
# STREAMING MODELS (§6.3)
# ═══════════════════════════════════════════════════════════════════════


class DeltaToolCall(BaseModel):
    """Incremental tool call in streaming."""
    index: int = 0
    id: str | None = None
    type: Literal["function"] | None = None
    function: FunctionCall | None = None


class DeltaMessage(BaseModel):
    """Delta in a streaming chunk — only changed fields present."""
    role: str | None = None
    content: str | None = None
    tool_calls: list[DeltaToolCall] | None = None


class StreamChoice(BaseModel):
    """A single choice in a streaming chunk."""
    index: int
    delta: DeltaMessage
    finish_reason: str | None = None
    logprobs: Logprobs | None = None


class ChatCompletionChunk(BaseModel):
    """
    A single SSE chunk in a streaming response.
    Object type: chat.completion.chunk.
    """
    id: str = Field(default_factory=lambda: f"chatcmpl-{uuid.uuid4().hex[:24]}")
    object: Literal["chat.completion.chunk"] = "chat.completion.chunk"
    created: int = Field(default_factory=lambda: int(time.time()))
    model: str = ""
    choices: list[StreamChoice] = Field(default_factory=list)
    usage: Usage | None = None

    model_config = {"extra": "allow"}

    def to_sse(self) -> str:
        """Serialize as SSE data line."""
        return f"data: {self.model_dump_json(exclude_none=True)}\n\n"

    @staticmethod
    def done_event() -> str:
        """Terminal SSE event."""
        return "data: [DONE]\n\n"


# ═══════════════════════════════════════════════════════════════════════
# MODELS LIST — /v1/models
# ═══════════════════════════════════════════════════════════════════════


class ModelObject(BaseModel):
    """A model object as returned by /v1/models."""
    id: str
    object: Literal["model"] = "model"
    created: int = Field(default_factory=lambda: int(time.time()))
    owned_by: str = "freerelay"


class ModelListResponse(BaseModel):
    """Response body for GET /v1/models."""
    object: Literal["list"] = "list"
    data: list[ModelObject] = Field(default_factory=list)
